homebb_docs:
  csv_filename: 'field_descriptions/RDK_AI_used_fields.csv'
  top_k: 10
RDK_parameters: ['serialnumber',
 'date',
 'time',
 'productclass',
 'manufacturer',
 'hardwareversion',
 'version',
 'telemetry_restart',
 'wifi_accesspoint_1_status',
 'wifi_accesspoint_2_status',
 'wifi_radio_1_status',
 'wifi_radio_2_status',
 'wifi_ssid_1_status',
 'wifi_ssid_2_status',
 'gpon_connectionstatus',
 'dhcpv4_server_pool_1_status',
 'ethernet_link_1_status',
#  'ethernet_interface_1_status',
#  'ethernet_interface_2_status',
#  'ethernet_interface_3_status',
#  'ethernet_interface_4_status',
#  'ethernet_interface_5_status',
 'ppp_interface_1_status',
 'ip_interface_1_status',
#  'ip_interface_1_ipv4address_1_status',
#  'ip_interface_1_ipv6address_1_status',
 'cpuusage',
 'cpu_temp_split',
 'wifi_radio_1_stats_noise',
 'wifi_radio_2_stats_noise',
 'wifi_radio_1_channel',
 'wifi_radio_2_channel',
 'wifi_radio_1_stats_x_comcast_com_channelutilization',
 'wifi_radio_2_stats_x_comcast_com_channelutilization',
 'wifi_radio_1_operatingchannelbandwidth',
 'wifi_radio_2_operatingchannelbandwidth',
 'wifi_ssid_1_stats_retranscount',
 'wifi_ssid_2_stats_retranscount',
 'gpon_rxsignallevel',
 'wifi_accesspoint_1_maxassociateddevices',
 'wifi_accesspoint_2_maxassociateddevices',
 'wifi_accesspoint_1_associateddevicenumberofentries',
 'wifi_accesspoint_2_associateddevicenumberofentries',
 'wifi_ssid_1_stats_errorssent',
#  'wifi_ssid_1_stats_errorsreceived',
 'wifi_ssid_2_stats_errorssent',
#  'wifi_ssid_2_stats_errorsreceived',
#  'wifi_ssid_1_stats_packetssent',
#  'wifi_ssid_1_stats_packetsreceived',
#  'wifi_ssid_2_stats_packetssent',
#  'wifi_ssid_2_stats_packetsreceived',
 'wifi_ssid_1_stats_bytesreceived',
 'wifi_ssid_1_stats_bytessent',
 'wifi_ssid_2_stats_bytesreceived',
 'wifi_ssid_2_stats_bytessent',
 'ppp_interface_1_stats_errorssent',
#  'ppp_interface_1_stats_errorsreceived',
 'ip_interface_1_stats_errorssent',
#  'ip_interface_1_stats_errorsreceived',
 'ip_interface_1_stats_bytessent',
 'ip_interface_1_stats_bytesreceived',
#  'ip_interface_1_reset',
 'ethernet_link_1_stats_bytessent',
 'ethernet_link_1_stats_bytesreceived',
 'ethernet_link_1_stats_errorsreceived',
 'ethernet_link_1_stats_errorssent',
 'wifi_ssid_1_stats_unknownprotopacketsreceived',
 'wifi_ssid_2_stats_unknownprotopacketsreceived',
 'hosts_connected_device_number',
 'wifi_radio_1_channelsinuse',
 'wifi_radio_2_channelsinuse',
 'ip_interface_1_ipv4enable',
 'ip_interface_1_ipv6enable',
 'change_wifi_radio_1_channel',
 'change_wifi_radio_2_channel',
 'memusage',
 'flash_usage_nvram_split_perc',
 'reboot_firmware_flag',
#  'empty_last_telemetry',
 'ip_interface_1_lastchange_flag',
 'ethernet_link_1_lastchange_flag',
 'is_reboot',
 'min_signalstrength',
 'max_signalstrength',
 'avg_signalstrength',
 'min_lastdatadownlinkrate',
 'max_lastdatadownlinkrate',
 'avg_lastdatadownlinkrate',
 'min_lastdatauplinkrate',
 'max_lastdatauplinkrate',
 'avg_lastdatauplinkrate',
 'total_band_change']