homebb_docs:
  csv_filename: 'field_descriptions/RDK_AI_used_fields.csv'
  top_k: 10
RDK_parameters: [
    # ============= IDENTITY & TEMPORAL =============
    'serialnumber',
    'date',
    'time',
    'productclass',
    'manufacturer',
    'hardwareversion',
    'version',
    
    # ============= REBOOT INDICATORS =============
    'is_reboot',
    'reboot_firmware_flag',
    'telemetry_restart',
    'last_reboot_reason_split',
    'deviceuptime',
    
    # ============= CPU & MEMORY =============
    'cpuusage',
    'cpu_temp_split',
    'memusage',
    'flash_usage_nvram_split_perc',
    'processnumberofentries',
    
    # ============= GPON / OPTICAL =============
    'gpon_rxsignallevel',
    'gpon_txsignallevel',
    'gpon_connectionstatus',
    'gpon_operationalstate',
    'gpon_registrationstate',
    'gpon_signalfail',
    'gpon_signaldegrade',
    
    # ============= WIFI RADIO 1 =============
    'wifi_radio_1_status',
    'wifi_radio_1_channel',
    'change_wifi_radio_1_channel',
    'wifi_radio_1_channelsinuse',
    'wifi_radio_1_stats_noise',
    'wifi_radio_1_stats_x_comcast_com_channelutilization',
    'wifi_radio_1_operatingchannelbandwidth',
    
    # ============= WIFI RADIO 2 =============
    'wifi_radio_2_status',
    'wifi_radio_2_channel',
    'change_wifi_radio_2_channel',
    'wifi_radio_2_channelsinuse',
    'wifi_radio_2_stats_noise',
    'wifi_radio_2_stats_x_comcast_com_channelutilization',
    'wifi_radio_2_operatingchannelbandwidth',
    
    # ============= WIFI ACCESS POINTS =============
    'wifi_accesspoint_1_status',
    'wifi_accesspoint_1_maxassociateddevices',
    'wifi_accesspoint_1_associateddevicenumberofentries',
    'wifi_accesspoint_2_status',
    'wifi_accesspoint_2_maxassociateddevices',
    'wifi_accesspoint_2_associateddevicenumberofentries',
    
    # ============= WIFI SSID 1 (with deltas) =============
    'wifi_ssid_1_status',
    'wifi_ssid_1_stats_retranscount',
    'wifi_ssid_1_stats_errorssent',
    'wifi_ssid_1_stats_errorssent_delta',
    'wifi_ssid_1_stats_errorsreceived',
    'wifi_ssid_1_stats_errorsreceived_delta',
    'wifi_ssid_1_stats_bytessent',
    'wifi_ssid_1_stats_bytessent_delta',
    'wifi_ssid_1_stats_bytesreceived',
    'wifi_ssid_1_stats_bytesreceived_delta',
    'wifi_ssid_1_stats_packetssent',
    'wifi_ssid_1_stats_packetssent_delta',
    'wifi_ssid_1_stats_packetsreceived',
    'wifi_ssid_1_stats_packetsreceived_delta',
    
    # ============= WIFI SSID 2 (with deltas) =============
    'wifi_ssid_2_status',
    'wifi_ssid_2_stats_retranscount',
    'wifi_ssid_2_stats_errorssent',
    'wifi_ssid_2_stats_errorssent_delta',
    'wifi_ssid_2_stats_errorsreceived',
    'wifi_ssid_2_stats_errorsreceived_delta',
    'wifi_ssid_2_stats_bytessent',
    'wifi_ssid_2_stats_bytessent_delta',
    'wifi_ssid_2_stats_bytesreceived',
    'wifi_ssid_2_stats_bytesreceived_delta',
    'wifi_ssid_2_stats_packetssent',
    'wifi_ssid_2_stats_packetssent_delta',
    'wifi_ssid_2_stats_packetsreceived',
    'wifi_ssid_2_stats_packetsreceived_delta',
    
    # ============= WIFI AGGREGATED =============
    'total_band_change',
    'min_signalstrength',
    'max_signalstrength',
    'avg_signalstrength',
    'min_lastdatadownlinkrate',
    'max_lastdatadownlinkrate',
    'avg_lastdatadownlinkrate',
    'min_lastdatauplinkrate',
    'max_lastdatauplinkrate',
    'avg_lastdatauplinkrate',
    
    # ============= PPP INTERFACE (with deltas) =============
    'ppp_interface_1_status',
    'ppp_interface_1_stats_errorssent',
    'ppp_interface_1_stats_errorssent_delta',
    'ppp_interface_1_stats_errorsreceived',
    'ppp_interface_1_stats_errorsreceived_delta',
    'ppp_interface_1_stats_bytessent',
    'ppp_interface_1_stats_bytessent_delta',
    'ppp_interface_1_stats_bytesreceived',
    'ppp_interface_1_stats_bytesreceived_delta',
    'ppp_interface_1_stats_packetssent',
    'ppp_interface_1_stats_packetssent_delta',
    'ppp_interface_1_stats_packetsreceived',
    'ppp_interface_1_stats_packetsreceived_delta',
    
    # ============= IP INTERFACE (with deltas) =============
    'ip_interface_1_status',
    'ip_interface_1_lastchange',
    'ip_interface_1_lastchange_flag',
    'ip_interface_1_stats_errorssent',
    'ip_interface_1_stats_errorssent_delta',
    'ip_interface_1_stats_errorsreceived',
    'ip_interface_1_stats_errorsreceived_delta',
    'ip_interface_1_stats_bytessent',
    'ip_interface_1_stats_bytessent_delta',
    'ip_interface_1_stats_bytesreceived',
    'ip_interface_1_stats_bytesreceived_delta',
    'ip_interface_1_stats_packetssent',
    'ip_interface_1_stats_packetssent_delta',
    'ip_interface_1_stats_packetsreceived',
    'ip_interface_1_stats_packetsreceived_delta',
    
    # ============= ETHERNET LINK (with deltas) =============
    'ethernet_link_1_status',
    'ethernet_link_1_lastchange',
    'ethernet_link_1_lastchange_flag',
    'ethernet_link_1_stats_errorssent',
    'ethernet_link_1_stats_errorssent_delta',
    'ethernet_link_1_stats_errorsreceived',
    'ethernet_link_1_stats_errorsreceived_delta',
    'ethernet_link_1_stats_bytessent',
    'ethernet_link_1_stats_bytessent_delta',
    'ethernet_link_1_stats_bytesreceived',
    'ethernet_link_1_stats_bytesreceived_delta',
    'ethernet_link_1_stats_packetssent',
    'ethernet_link_1_stats_packetssent_delta',
    'ethernet_link_1_stats_packetsreceived',
    'ethernet_link_1_stats_packetsreceived_delta',
    
    # ============= DSL LINE (with deltas) =============
    'dsl_line_1_stats_bytessent',
    'dsl_line_1_stats_bytessent_delta',
    'dsl_line_1_stats_bytesreceived',
    'dsl_line_1_stats_bytesreceived_delta',
    'dsl_line_1_stats_errorssent',
    'dsl_line_1_stats_errorssent_delta',
    'dsl_line_1_stats_errorsreceived',
    'dsl_line_1_stats_errorsreceived_delta',
    'dsl_line_1_stats_packetssent',
    'dsl_line_1_stats_packetssent_delta',
    'dsl_line_1_stats_packetsreceived',
    'dsl_line_1_stats_packetsreceived_delta',
    
    # ============= DSL CHANNEL =============
    'dsl_channel_1_stats_packetsreceived',
    'dsl_channel_1_stats_packetssent',
    
    # ============= WAN (with deltas) =============
    'wan_bytessent',
    'wan_bytessent_delta',
    'wan_bytesreceived',
    'wan_bytesreceived_delta',
    'wan_errorssent',
    'wan_errorssent_delta',
    'wan_errorsreceived',
    'wan_errorsreceived_delta',
    'wan_packetssent',
    'wan_packetssent_delta',
    'wan_packetsreceived',
    'wan_packetsreceived_delta',
    
    # ============= DHCP & NAT =============
    'dhcpv4_server_pool_1_status',
    'nat_portmappingnoofentries',
    
    # ============= DEVICE LOAD =============
    'hosts_connected_device_number',
    'n_devices',
    
    # ============= FLAGS =============
    'empty_last_telemetry',
]